name: Setup MySQL Connector
description: Download and configure MySQL Connector/C++
inputs:
  version:
    description: "MySQL Connector/C++ archive name"
    required: false
    default: mysql-connector-c++-9.4.0-macos15-arm64
runs:
  using: composite
  steps:
    - name: Download connector
      shell: bash
      run: |
        set -euo pipefail
        MYSQL_VER="${{ inputs.version }}"
        MYSQL_URL="https://dev.mysql.com/get/Downloads/Connector-C++/${MYSQL_VER}.tar.gz"
        curl -LO "$MYSQL_URL"
        tar -xf "${MYSQL_VER}.tar.gz"
    - name: Export environment variables
      shell: bash
      run: |
        set -euo pipefail
        CONN_DIR="${PWD}/${{ inputs.version }}"
        LIBDIR="lib64"
        if [ ! -d "$CONN_DIR/$LIBDIR" ]; then
          LIBDIR="lib"
        fi
        export PATH="$CONN_DIR/bin:$PATH"
        export CPPFLAGS="-I$CONN_DIR/include $CPPFLAGS"
        export LDFLAGS="-L$CONN_DIR/$LIBDIR $LDFLAGS"
        export PKG_CONFIG_PATH="$CONN_DIR/$LIBDIR/pkgconfig:$PKG_CONFIG_PATH"
        DYLD_LIBRARY_PATH="${DYLD_LIBRARY_PATH:-}"
        export DYLD_LIBRARY_PATH="$CONN_DIR/$LIBDIR:$DYLD_LIBRARY_PATH"
        echo "PATH=$PATH" >> $GITHUB_ENV
        echo "CPPFLAGS=$CPPFLAGS" >> $GITHUB_ENV
        echo "LDFLAGS=$LDFLAGS" >> $GITHUB_ENV
        echo "PKG_CONFIG_PATH=$PKG_CONFIG_PATH" >> $GITHUB_ENV
        echo "DYLD_LIBRARY_PATH=$DYLD_LIBRARY_PATH" >> $GITHUB_ENV
