---
name: Build and Test
description: Checkout repository, install dependencies, build, and upload artifacts
inputs:
  distro:
    description: "Target distribution"
    required: true
runs:
  using: composite
  steps:
    - uses: actions/checkout@v4
    - name: Install dependencies (Debian/Ubuntu)
      if: ${{ contains('debian-12 debian-13 ubuntu-24.04 ubuntu-22.04', inputs.distro) }}
      shell: bash
      run: |
        SUDO=""
        command -v sudo >/dev/null 2>&1 && SUDO="sudo"
        
        $SUDO apt-get update
        
        # Install wget first if needed for Debian MySQL repository setup
        if [[ "${{ inputs.distro }}" == "debian-12" || "${{ inputs.distro }}" == "debian-13" ]]; then
          $SUDO apt-get install -y wget
          wget https://dev.mysql.com/get/mysql-apt-config_0.8.32-1_all.deb
          echo "mysql-apt-config mysql-apt-config/select-server select mysql-8.0" | $SUDO debconf-set-selections
          $SUDO dpkg -i mysql-apt-config_0.8.32-1_all.deb || true
          $SUDO apt-get update
        fi
        $SUDO apt-get install -y \
          build-essential \
          autoconf automake libtool pkg-config \
          gettext \
          autopoint \
          libxml2-dev libcurl4-openssl-dev \
          libmysqlclient-dev mariadb-client libpq-dev libmicrohttpd-dev wget
        wget https://ftp.gnu.org/pub/gnu/gettext/gettext-0.22.tar.gz
        tar -xf gettext-0.22.tar.gz
        cd gettext-0.22
        ./configure --disable-shared
        make -j$(nproc)
        $SUDO make install
        cd ..
        echo "PATH=/usr/local/bin:$PATH" >> $GITHUB_ENV
        if [[ "${{ inputs.distro }}" == "debian-12" || "${{ inputs.distro }}" == "debian-13" ]]; then
          wget https://dev.mysql.com/get/Downloads/Connector-C++/libmysqlcppconnx2-dbgsym_9.4.0-1debian12_amd64.deb
          wget https://dev.mysql.com/get/Downloads/Connector-C++/libmysqlcppconn10_9.4.0-1debian12_amd64.deb
          wget https://dev.mysql.com/get/Downloads/Connector-C++/libmysqlcppconnx2_9.4.0-1debian12_amd64.deb
          wget https://dev.mysql.com/get/Downloads/Connector-C++/libmysqlcppconn-dev_9.4.0-1debian12_amd64.deb
          $SUDO dpkg -i libmysqlcppconn10_9.4.0-1debian12_amd64.deb libmysqlcppconnx2_9.4.0-1debian12_amd64.deb libmysqlcppconnx2-dbgsym_9.4.0-1debian12_amd64.deb libmysqlcppconn-dev_9.4.0-1debian12_amd64.deb || true
          $SUDO apt-get -f install -y
        elif [[ "${{ inputs.distro }}" == "ubuntu-24.04" ]]; then
          wget https://dev.mysql.com/get/Downloads/Connector-C++/libmysqlcppconn10_9.4.0-1ubuntu24.04_amd64.deb
          wget https://dev.mysql.com/get/Downloads/Connector-C++/libmysqlcppconnx2_9.4.0-1ubuntu24.04_amd64.deb
          wget https://dev.mysql.com/get/Downloads/Connector-C++/libmysqlcppconn-dev_9.4.0-1ubuntu24.04_amd64.deb
          $SUDO dpkg -i libmysqlcppconn10_9.4.0-1ubuntu24.04_amd64.deb libmysqlcppconnx2_9.4.0-1ubuntu24.04_amd64.deb libmysqlcppconn-dev_9.4.0-1ubuntu24.04_amd64.deb || true
          $SUDO apt-get -f install -y
        else
          wget https://dev.mysql.com/get/Downloads/Connector-C++/libmysqlcppconn10_9.4.0-1ubuntu22.04_amd64.deb
          wget https://dev.mysql.com/get/Downloads/Connector-C++/libmysqlcppconnx2_9.4.0-1ubuntu22.04_amd64.deb
          wget https://dev.mysql.com/get/Downloads/Connector-C++/libmysqlcppconn-dev_9.4.0-1ubuntu22.04_amd64.deb
          $SUDO dpkg -i libmysqlcppconn10_9.4.0-1ubuntu22.04_amd64.deb libmysqlcppconnx2_9.4.0-1ubuntu22.04_amd64.deb libmysqlcppconn-dev_9.4.0-1ubuntu22.04_amd64.deb || true
          $SUDO apt-get -f install -y
        fi
        INC=/usr/include/mysql-cppconn/jdbc
        LIB=/usr/lib/x86_64-linux-gnu
        export CPPFLAGS="-I$INC $CPPFLAGS"
        export LDFLAGS="-L$LIB $LDFLAGS"
        export PKG_CONFIG_PATH="$LIB/pkgconfig:$PKG_CONFIG_PATH"
        echo "CPPFLAGS=$CPPFLAGS" >> $GITHUB_ENV
        echo "LDFLAGS=$LDFLAGS" >> $GITHUB_ENV
        echo "PKG_CONFIG_PATH=$PKG_CONFIG_PATH" >> $GITHUB_ENV
    - name: Install dependencies (macOS)
      if: ${{ inputs.distro == 'macos-14' }}
      shell: bash
      run: |
        brew update
        brew install \
          autoconf automake libtool pkg-config gettext \
          libxml2 curl mysql-client libpq libmicrohttpd
        B=/opt/homebrew/opt
        export PKG_CONFIG_PATH=$B/libxml2/lib/pkgconfig:$PKG_CONFIG_PATH
        export PKG_CONFIG_PATH=$B/mysql-client/lib/pkgconfig:$PKG_CONFIG_PATH
        export PKG_CONFIG_PATH=$B/libpq/lib/pkgconfig:$PKG_CONFIG_PATH
        export PATH=$B/mysql-client/bin:$PATH
        export PATH=$B/gettext/bin:$PATH
        export CPPFLAGS=-I$B/mysql-client/include $CPPFLAGS
        export LDFLAGS=-L$B/mysql-client/lib $LDFLAGS
        echo "PATH=$PATH" >> $GITHUB_ENV
        echo "CPPFLAGS=$CPPFLAGS" >> $GITHUB_ENV
        echo "LDFLAGS=$LDFLAGS" >> $GITHUB_ENV
        echo "PKG_CONFIG_PATH=$PKG_CONFIG_PATH" >> $GITHUB_ENV
    - name: Setup MySQL Connector
      if: ${{ inputs.distro == 'macos-14' }}
      uses: ./.github/actions/setup-mysql-connector
      with:
        version: mysql-connector-c++-9.4.0-macos15-arm64
    - name: Show environment variables
      if: ${{ inputs.distro == 'macos-14' }}
      shell: bash
      run: |
        echo "PATH=$PATH"
        echo "CPPFLAGS=$CPPFLAGS"
        echo "LDFLAGS=$LDFLAGS"
        echo "PKG_CONFIG_PATH=$PKG_CONFIG_PATH"
        echo "DYLD_LIBRARY_PATH=$DYLD_LIBRARY_PATH"
    - name: Verify autopoint
      shell: bash
      run: autopoint --version
    - name: Run autogen script
      shell: bash
      run: |
        set -o pipefail
        ./autogen.sh 2>&1 | tee autogen.log
    - name: Configure
      shell: bash
      run: |
        set -o pipefail
        ./configure 2>&1 | tee configure.log
    - name: Build
      shell: bash
      run: |
        set -o pipefail
        make 2>&1 | tee build.log
    - name: Test
      shell: bash
      run: |
        set -o pipefail
        make check 2>&1 | tee test.log
    - name: Verify scastd --help
      shell: bash
      run: |
        set -e
        ./src/scastd --help > scastd-help.log 2>&1
        cat scastd-help.log
    - name: Upload build artifacts and logs
      if: ${{ always() }}
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.distro }}-logs
        path: |
          autogen.log
          configure.log
          build.log
          test.log
          scastd-help.log
          config.log
          src/scastd
          src/.libs/scastd
        if-no-files-found: ignore
