name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test:
    name: Build and test
    strategy:
      matrix:
        include:
          - os: ubuntu-24.04
            arch: x64
          - os: macos-14
            arch: arm64
    runs-on: ${{ matrix.os }}
    architecture: ${{ matrix.arch }}
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies (Ubuntu)
        if: matrix.os == 'ubuntu-24.04'
        run: sudo apt-get update && sudo apt-get install -y build-essential autoconf automake libtool pkg-config libxml2-dev libcurl4-openssl-dev libmysqlclient-dev libpq-dev libmicrohttpd-dev
      - name: Install dependencies (macOS)
        if: matrix.os == 'macos-14'
        run: |
          brew update
          brew install autoconf automake libtool pkg-config libxml2 curl mysql-client libpq libmicrohttpd
          echo "PKG_CONFIG_PATH=/opt/homebrew/opt/libpq/lib/pkgconfig:/opt/homebrew/opt/mysql-client/lib/pkgconfig:/opt/homebrew/opt/libxml2/lib/pkgconfig:$PKG_CONFIG_PATH" >> $GITHUB_ENV
      - name: Generate configure script
        run: ./autogen.sh
      - name: Configure
        run: ./configure
      - name: Build
        run: make
      - name: Run unit tests
        run: make check

  lint:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Install cppcheck
        run: sudo apt-get update && sudo apt-get install -y cppcheck
      - name: Run cppcheck
        run: cppcheck --enable=all --std=c++17 --suppress=missingIncludeSystem src tests

