---
name: DevelopmentBuildPipeline

"on":
  push:
    branches: ["dev"]
  pull_request:
    branches: ["dev"]

permissions:
  contents: write

jobs:
  test:
    name: Build and test (${{ matrix.distro }})
    strategy:
      fail-fast: false
      matrix:
        distro: [debian-12, debian-13, ubuntu-24.04, ubuntu-22.04, macos-14]
        include:
          - distro: debian-12
            os: ubuntu-22.04
            container: debian:12
          - distro: debian-13
            os: ubuntu-22.04
            container: debian:trixie
          - distro: ubuntu-24.04
            os: ubuntu-24.04
          - distro: ubuntu-22.04
            os: ubuntu-22.04
          - distro: macos-14
            os: macos-14
    runs-on: ${{ matrix.os }}
    container: ${{ matrix.container }}
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/build-and-test
        with:
          distro: ${{ matrix.distro }}

  lint:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Install cppcheck
        run: sudo apt-get update && sudo apt-get install -y cppcheck
      - name: Run cppcheck
        run: |
          cppcheck --enable=all --std=c++17 \
            --suppress=missingIncludeSystem \
            src
  release:
    needs: [test, lint]
    if: github.ref == 'refs/heads/dev' && github.event_name == 'push'
    strategy:
      matrix:
        include:
          - os: ubuntu-24.04
            build_script: packaging/debian/build_deb.sh
            checksum: sha256sum
          - os: macos-14
            build_script: packaging/macos/build_pkg.sh
            checksum: "shasum -a 256"
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Build packages
        run: |
          chmod +x ${{ matrix.build_script }}
          ${{ matrix.build_script }} ${{ github.run_number }}
      - name: Generate checksums
        run: |
          for file in dist/*; do
            ${{ matrix.checksum }} "$file" > "$file.sha256"
          done
      - name: Upload release assets
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ github.run_number }}
          name: Release ${{ github.run_number }}
          draft: false
          prerelease: true
          files: dist/*
