---
name: ProductionBuildDeployment

"on":
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

permissions:
  contents: write

jobs:
  test:
    name: Build and test (${{ matrix.distro }})
    strategy:
      fail-fast: false
      matrix:
        distro: [debian-12, debian-13, ubuntu-24.04, ubuntu-22.04, macos-14]
        include:
          - distro: debian-12
            os: ubuntu-22.04
            container: debian:12
          - distro: debian-13
            os: ubuntu-22.04
            container: debian:trixie
          - distro: ubuntu-24.04
            os: ubuntu-24.04
          - distro: ubuntu-22.04
            os: ubuntu-22.04
          - distro: macos-14
            os: macos-14
    runs-on: ${{ matrix.os }}
    container: ${{ matrix.container }}
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/build-and-test
        with:
          distro: ${{ matrix.distro }}

  lint:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Install cppcheck
        run: sudo apt-get update && sudo apt-get install -y cppcheck
      - name: Run cppcheck
        run: |
          cppcheck --enable=all --std=c++17 \
            --suppress=missingIncludeSystem \
            src
  release:
    needs: [test, lint]
    runs-on: ubuntu-24.04
    if: github.ref == 'refs/heads/master' && github.event_name == 'push'
    steps:
      - name: Create GitHub release
        if: success()
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.GH_PAT }}
          tag_name: v${{ github.run_number }}
          name: Release ${{ github.run_number }}
          draft: true
          prerelease: false
      - name: Verify release
        env:
          TAG: v${{ github.run_number }}
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
        run: |
          set -euo pipefail
          response=$(curl -sSf -H "Authorization: Bearer $GITHUB_TOKEN" \
                         -H "Accept: application/vnd.github+json" \
                         https://api.github.com/repos/${GITHUB_REPOSITORY}/releases/tags/$TAG)
          url=$(echo "$response" | jq -r '.html_url')
          assets=$(echo "$response" | jq '.assets | length')
          if [ "$assets" -eq 0 ]; then
            echo "::error::Release has no assets"
            exit 1
          fi
          echo "Release URL: $url"
